### PR TITLE
loosing messages on ZMQListener

### PR DESCRIPTION
**Pull request by golanha**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/51)

### CODE REVIEW

**Review by NassiHarel — CHANGES_REQUESTED** [review]
:lgtm:

> Reviewed 7 of 7 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/51#-:-MRVHxXNBzGW54XplqXz:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @golanha)

___
*[hkube_python_wrapper/wrapper/algorunner.py, line 415 at r2](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/51#-MRYqmr-422781UHxz4t:-MRYqmr-422781UHxz4u:bdme2cz) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/b328c7e6d295e6bae3b3b825d09b97297ba8683b/hkube_python_wrapper/wrapper/algorunner.py#L415)):*
> ```
> options['forceStop']
> ```
This will throw an error if for any reason there is no such property `forceStop`

**Review by golanha — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/51)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @NassiHarel)

___
*[hkube_python_wrapper/wrapper/algorunner.py, line 415 at r2](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/51#-MRYqmr-422781UHxz4t:-MRYzGitBIjnkauN0zgp:b-896fix) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/b328c7e6d295e6bae3b3b825d09b97297ba8683b/hkube_python_wrapper/wrapper/algorunner.py#L415)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> options['forceStop']
> ```
This will throw an error if for any reason there is no such property `forceStop`
</blockquote></details>

Done.

**Review by NassiHarel — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/51#-:-MRZAX6w-OKOpC4MS9Kq:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by NassiHarel — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/51)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @golanha and @NassiHarel)

___
*[tests/test_streaming.py, line 107 at r4](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/51#-MR_EZS1BcavWpyzoGWk:-MR_EZS27zVnX53h5hJx:b-d9fuwa) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/0cd6f5fa11d8c19c852576406be358511802587a/tests/test_streaming.py#L107)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
>         for _ in range(1,60):
>             if ( asserts.get('field1')):
>                 break
>             time.sleep(1)
>         time.sleep(5)
> ```
</details>


So this test can take up to 65 seconds?
You can limit that to a max of 5 sec?

**Review by golanha — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/51)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @NassiHarel)

___
*[tests/test_streaming.py, line 107 at r4](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/51#-MR_EZS1BcavWpyzoGWk:-MR_H_wSCzTa_4IL5Gfi:bjlojfr) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/0cd6f5fa11d8c19c852576406be358511802587a/tests/test_streaming.py#L107)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
>         for _ in range(1,60):
>             if ( asserts.get('field1')):
>                 break
>             time.sleep(1)
>         time.sleep(5)
> ```

So this test can take up to 65 seconds?
You can limit that to a max of 5 sec?
</blockquote></details>

It will usually take 5 seconds.
I limit it to 9

**Review by NassiHarel — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/51)* status: 7 of 8 files reviewed, 2 unresolved discussions (waiting on @golanha and @NassiHarel)

___
*[tests/test_streaming.py, line 132 at r5](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/51#-MR_K58Y6NcLkEOaRkER:-MR_K58Z1bd7VE-vSStU:b5hgtru) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/eb93aff97db629558d54fa3cbf590034e7d31240/tests/test_streaming.py#L132)):*
> ```
> time.sleep(5)
> ```
Do you like to sleep?

You have 7 sleeps in this test.....

**Review by golanha — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/51)* status: 7 of 8 files reviewed, 2 unresolved discussions (waiting on @NassiHarel)

___
*[tests/test_streaming.py, line 132 at r5](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/51#-MR_K58Y6NcLkEOaRkER:-MRnGvdU2vIhe4a_wzBX:buj595e) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/eb93aff97db629558d54fa3cbf590034e7d31240/tests/test_streaming.py#L132)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> time.sleep(5)
> ```
Do you like to sleep?

You have 7 sleeps in this test.....
</blockquote></details>

I removed an unneeded sleep.

**Review by NassiHarel — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/51#-:-MRnItNUAWH3TvFJey2x:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
