### PR TITLE
Losing messages

### PR DESCRIPTION
**Pull request by golanha**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/54)

### CODE REVIEW

**Review by NassiHarel — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/54)* status: 2 of 5 files reviewed, 3 unresolved discussions (waiting on @golanha and @yehiyam)

___
*[hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py, line 109 at r1](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/54#-MScZlyZAJiFHCpI6JKM:-MScZlyZAJiFHCpI6JKN:b-2a1nl3) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/0a6ec52ffbdecc48e47e026ac295ff68a37190bb/hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py#L109)):*
> ```
> self.worker.setsockopt(zmq.LINGER, 0)
> ```
No need
___
*[hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py, line 88 at r2](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/54#-MT5WFtY1ma3QUQDaKV3:-MT5WFtZ8GofEDGUxqql:b-9jhgnx) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/a48bcf16626ff0659be3532070f13e6eeba49bbc/hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py#L88)):*
> ```
> result = self.handleAMessage(frames)
> ```
If you have an exception here, the lock will be released?
___
*[hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py, line 159 at r2](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/54#-MT5Wk9eBrrwl8FIlA_s:-MT5Wk9eBrrwl8FIlA_t:btxmx3z) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/a48bcf16626ff0659be3532070f13e6eeba49bbc/hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py#L159)):*
> ```
>                                 encodedMessageFlowPattern, header, message = frames  # pylint: disable=unbalanced-tuple-unpacking
>                                 messageFlowPattern = self.encoding.decode(value=encodedMessageFlowPattern, plainEncode=True)
>                                 self.onMessage(messageFlowPattern, header, message)
> ```

Not duplicate?

**Review by golanha — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/54)* status: 2 of 5 files reviewed, 3 unresolved discussions (waiting on @NassiHarel and @yehiyam)

___
*[hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py, line 109 at r1](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/54#-MScZlyZAJiFHCpI6JKM:-MT5sow2DdWpygIT-E1O:b-896fix) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/0a6ec52ffbdecc48e47e026ac295ff68a37190bb/hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py#L109)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> self.worker.setsockopt(zmq.LINGER, 0)
> ```
No need
</blockquote></details>

Done.
___
*[hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py, line 88 at r2](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/54#-MT5WFtY1ma3QUQDaKV3:-MT5qXcUCsKIBYtLO4XH:b-x1b7h7) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/a48bcf16626ff0659be3532070f13e6eeba49bbc/hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py#L88)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> result = self.handleAMessage(frames)
> ```
If you have an exception here, the lock will be released?
</blockquote></details>

yes, I want to allow the rest of the MessageListers to continue handle messages
___
*[hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py, line 159 at r2](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/54#-MT5Wk9eBrrwl8FIlA_s:-MT5spXb5zaHU01HiTRh:b-896fix) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/a48bcf16626ff0659be3532070f13e6eeba49bbc/hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py#L159)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
>                                 encodedMessageFlowPattern, header, message = frames  # pylint: disable=unbalanced-tuple-unpacking
>                                 messageFlowPattern = self.encoding.decode(value=encodedMessageFlowPattern, plainEncode=True)
>                                 self.onMessage(messageFlowPattern, header, message)
> ```

Not duplicate?
</blockquote></details>

Done.

**Review by NassiHarel — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/54)* status: 2 of 5 files reviewed, 4 unresolved discussions (waiting on @golanha, @NassiHarel, and @yehiyam)

___
*[hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py, line 88 at r2](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/54#-MT5WFtY1ma3QUQDaKV3:-MT6O2BDCV3akcjHDGHt:bq8ka7l) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/a48bcf16626ff0659be3532070f13e6eeba49bbc/hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py#L88)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

yes, I want to allow the rest of the MessageListers to continue handle messages
</blockquote></details>

But you `lock.release()` after `self.handleAMessage(frames)`
___
*[hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py, line 82 at r3](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/54#-MT6Nk40C8MFRNuniChQ:-MT6Nk40C8MFRNuniChR:bs9l69b) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/e851c1922596b363671c46a4c4e912a6f6c4d7ca/hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py#L82)):*
> ```
> if (self.active):
> ```
Here you don't  `lock.release()`

**Review by NassiHarel — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/54)* status: 2 of 5 files reviewed, 5 unresolved discussions (waiting on @golanha, @NassiHarel, and @yehiyam)

___
*[hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py, line 150 at r3](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/54#-MT6OLZ88EUQpL5UAbQ7:-MT6OLZ88EUQpL5UAbQ8:b2oq9du) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/e851c1922596b363671c46a4c4e912a6f6c4d7ca/hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py#L150)):*
<details><summary><i alt="summary">Quoted 11 lines of code…</i></summary>

> ```
>                     while result == zmq.POLLIN:
>                         frames = self.worker.recv_multipart()
>                         if len(frames) == 3:
>                             readAfterStopped += 1
>                             print('Read after stop ' + str(readAfterStopped))
>                         result = self.worker.poll(HEARTBEAT_INTERVAL * 1000)
>                         while result == zmq.POLLIN:
>                             lock.acquire()
>                             frames = self.worker.recv_multipart()
>                             if len(frames) == 3:
>                                 self.handleAMessage(frames)
> ```
</details>


Why there is almost the same code here?

**Review by NassiHarel — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/54)* status: 2 of 5 files reviewed, 6 unresolved discussions (waiting on @golanha, @NassiHarel, and @yehiyam)

___
*[hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py, line 88 at r3](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/54#-MT6OuktDX4_BqCepYDW:-MT6OuktDX4_BqCepYDX:bl5hmcq) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/e851c1922596b363671c46a4c4e912a6f6c4d7ca/hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py#L88)):*
> ```
> result = self.handleAMessage(frames)
> ```
If this throws, you don't `lock.release()`

**Review by golanha — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/54)* status: 2 of 5 files reviewed, 6 unresolved discussions (waiting on @NassiHarel and @yehiyam)

___
*[hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py, line 88 at r2](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/54#-MT5WFtY1ma3QUQDaKV3:-MT7Kt-XErDzXW2uq33x:bkvqjh2) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/a48bcf16626ff0659be3532070f13e6eeba49bbc/hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py#L88)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

But you `lock.release()` after `self.handleAMessage(frames)`
</blockquote></details>

but i don't get there in case of an exception, right?
___
*[hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py, line 82 at r3](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/54#-MT6Nk40C8MFRNuniChQ:-MT7KrEtEOEChftOuoo9:b-896fix) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/e851c1922596b363671c46a4c4e912a6f6c4d7ca/hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py#L82)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> if (self.active):
> ```
Here you don't  `lock.release()`
</blockquote></details>

Done.
___
*[hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py, line 88 at r3](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/54#-MT6OuktDX4_BqCepYDW:-MT7L-Cq8cttQ3q4dWLq:b-896fix) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/e851c1922596b363671c46a4c4e912a6f6c4d7ca/hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py#L88)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> result = self.handleAMessage(frames)
> ```
If this throws, you don't `lock.release()`
</blockquote></details>

Done.
___
*[hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py, line 150 at r3](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/54#-MT6OLZ88EUQpL5UAbQ7:-MT6idab5JB83nv63z1s:b-lub0ol) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/e851c1922596b363671c46a4c4e912a6f6c4d7ca/hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py#L150)):*
> result = self.handleAMessage(frames)
Big Bug!! reason for lost messages. I just found it myself a minute ago.

**Review by NassiHarel — APPROVED** [review]
:lgtm:

> Reviewed 2 of 4 files at r1, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/54#-:-MT9lo8i3s7FJmsYzxUi:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yehiyam)

**Pull request merged**
