### PR TITLE
Put messages with recipient only

### PR DESCRIPTION
**Pull request by golanha**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/61)

### CODE REVIEW

**Review by NassiHarel — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/61)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @golanha)

___
*[hkube_python_wrapper/communication/zmq/streaming/producer/MessageQueue.py, line 87 at r1](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/61#-MUEHP0R1hub7qj0jLwe:-MUEHP0R1hub7qj0jLwf:b-immg0e) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/71b4f7823177f205ba556982140f6117852e39f1/hkube_python_wrapper/communication/zmq/streaming/producer/MessageQueue.py#L87)):*
> ```
> return 
> ```
1. Why do you `return` from this function?
2. if the message doesn't go into the queue, where does it go?

**Review by golanha — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/61)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @NassiHarel)

___
*[hkube_python_wrapper/communication/zmq/streaming/producer/MessageQueue.py, line 87 at r1](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/61#-MUEHP0R1hub7qj0jLwe:-MUEOH2f8GbQa97MbYOv:b-ueuzks) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/71b4f7823177f205ba556982140f6117852e39f1/hkube_python_wrapper/communication/zmq/streaming/producer/MessageQueue.py#L87)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> return 
> ```
1. Why do you `return` from this function?
2. if the message doesn't go into the queue, where does it go?
</blockquote></details>

1. You are right there is no need to return a value. Done
2. This message is not meant for anyone. Its the last node in a flow.

**Review by NassiHarel — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, 2 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/61)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @golanha and @NassiHarel)

___
*[hkube_python_wrapper/communication/zmq/streaming/producer/MessageQueue.py, line 59 at r3](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/61#-MUJNYZ_AmEKDQw5KjmT:-MUJNYZ_AmEKDQw5KjmU:b-w28os1) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/ad4d945d473fd11ab76a6973652ba9bfae22e83a/hkube_python_wrapper/communication/zmq/streaming/producer/MessageQueue.py#L59)):*
> ```
> otherConsumerType, otherIndex
> ```
Why its called `other`?
___
*[hkube_python_wrapper/communication/zmq/streaming/producer/ZMQProducer.py, line 131 at r3](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/61#-MUJCexF5vDv3FH8pAbM:-MUJCexF5vDv3FH8pAbN:b-p87p96) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/ad4d945d473fd11ab76a6973652ba9bfae22e83a/hkube_python_wrapper/communication/zmq/streaming/producer/ZMQProducer.py#L131)):*
> ```
> log.info('queue size during close = ' + str(len(self.messageQueue.queue)))
> ```

put this before the loop, and one log after loop...

**Review by golanha — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/61)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @NassiHarel)

___
*[hkube_python_wrapper/communication/zmq/streaming/producer/MessageQueue.py, line 59 at r3](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/61#-MUJNYZ_AmEKDQw5KjmT:-MUJVZW64yTWtIou2MIC:b-6tyy8l) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/ad4d945d473fd11ab76a6973652ba9bfae22e83a/hkube_python_wrapper/communication/zmq/streaming/producer/MessageQueue.py#L59)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> otherConsumerType, otherIndex
> ```
Why its called `other`?
</blockquote></details>

Its a mistake I'll remove it.
___
*[hkube_python_wrapper/communication/zmq/streaming/producer/ZMQProducer.py, line 131 at r3](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/61#-MUJCexF5vDv3FH8pAbM:-MUJX6vdCTPZinhAN4cw:b-896fix) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/ad4d945d473fd11ab76a6973652ba9bfae22e83a/hkube_python_wrapper/communication/zmq/streaming/producer/ZMQProducer.py#L131)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> log.info('queue size during close = ' + str(len(self.messageQueue.queue)))
> ```

put this before the loop, and one log after loop...
</blockquote></details>

Done.

**Review by NassiHarel — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/61#-:-MUMvvWT3h6IbY_r0EeT:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
