### PR TITLE
allow ssl_no_verify for s3

### PR DESCRIPTION
**Pull request by yehiyam**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/81)

### CODE REVIEW

**Comment by yehiyam** [comment]
fixes https://github.com/kube-HPC/hkube/issues/1454

**Review by NassiHarel — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/81)* status: all files reviewed, 1 unresolved discussion (waiting on @yehiyam)

___
*[tests/configs/config.py, line 44 at r1](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/81#-Mp5akgo-qnWWiimO5f3:-Mp5akgp6zqvNFb_BqmW:b-jqyl1e) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/dfbe7367098cb7aecb315d2a77ed3da02cec01ee/tests/configs/config.py#L44)):*
> ```
> "verify_ssl": getBoolEnv('S3_VERIFY_SSL', 'False')
> ```
Do u have a unit test for this?

**Review by yehiyam — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/81)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @NassiHarel)

___
*[tests/configs/config.py, line 44 at r1](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/81#-Mp5akgo-qnWWiimO5f3:-MpC8KaCEjOtrtH0DDGk:b-896fix) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/dfbe7367098cb7aecb315d2a77ed3da02cec01ee/tests/configs/config.py#L44)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> "verify_ssl": getBoolEnv('S3_VERIFY_SSL', 'False')
> ```
Do u have a unit test for this?
</blockquote></details>

Done.

**Review by NassiHarel — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/81#-:-MpCC3OTBJLP9TfACGer:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yehiyam)

**Pull request merged**
