### PR TITLE
send header separately using multipart

### PR DESCRIPTION
**Pull request by golanha**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/27)

### CODE REVIEW

**Review by NassiHarel — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/27)* status: all files reviewed, 2 unresolved discussions (waiting on @golanha)

___
*[hkube_python_wrapper/communication/DataRequest.py, line 28 at r2](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/27#-MHC-bl90nd60HP2Klg-:-MHC-blA4lwQO0wxdy0c:by4ipli) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/12ca770cb4a0b020dd0790987a7eec27adbfd90a/hkube_python_wrapper/communication/DataRequest.py#L28)):*
> ```
>  header = None
> ```
why you need it here?
___
*[hkube_python_wrapper/util/encoding.py, line 80 at r2](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/27#-MHC00ygEmwv8RgO8WK-:-MHC00ygEmwv8RgO8WK0:b-4dbatd) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/12ca770cb4a0b020dd0790987a7eec27adbfd90a/hkube_python_wrapper/util/encoding.py#L80)):*
> ```
> def encode_separately
> ```
You have a duplicate code...
look at: 
https://github.com/kube-HPC/encoding.hkube/blob/2f9d715d08b816dccbc1f092fda4caa6de132ca7/lib/encoding.js#L58

**Review by golanha — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/27)* status: all files reviewed, 2 unresolved discussions (waiting on @NassiHarel)

___
*[hkube_python_wrapper/communication/DataRequest.py, line 28 at r2](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/27#-MHC-bl90nd60HP2Klg-:-MHFC12v07BqDrqvOu6V:bmnnnpn) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/12ca770cb4a0b020dd0790987a7eec27adbfd90a/hkube_python_wrapper/communication/DataRequest.py#L28)):*
> ```
>  header = None
> ```
Removed
___
*[hkube_python_wrapper/util/encoding.py, line 80 at r2](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/27#-MHC00ygEmwv8RgO8WK-:-MHFSFQ-60Y2WvsJnc4m:b-apq7yi) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/12ca770cb4a0b020dd0790987a7eec27adbfd90a/hkube_python_wrapper/util/encoding.py#L80)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> def encode_separately
> ```
You have a duplicate code...
look at: 
https://github.com/kube-HPC/encoding.hkube/blob/2f9d715d08b816dccbc1f092fda4caa6de132ca7/lib/encoding.js#L58
</blockquote></details>

did the same as you

**Review by NassiHarel — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/27)* status: all files reviewed, 1 unresolved discussion (waiting on @golanha)

___
*[hkube_python_wrapper/util/encoding.py, line 80 at r2](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/27#-MHC00ygEmwv8RgO8WK-:-MHF_lWj7BwNyx-DllOK:b-deyjaj) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/12ca770cb4a0b020dd0790987a7eec27adbfd90a/hkube_python_wrapper/util/encoding.py#L80)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

did the same as you
</blockquote></details>

Still, duplicate code...

**Review by golanha — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/27)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @NassiHarel)

___
*[hkube_python_wrapper/util/encoding.py, line 80 at r2](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/27#-MHC00ygEmwv8RgO8WK-:-MHFrkLBCRWPoEUrMpUO:bvbqnob) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/12ca770cb4a0b020dd0790987a7eec27adbfd90a/hkube_python_wrapper/util/encoding.py#L80)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

Still, duplicate code...
</blockquote></details>

Not any more

**Review by yehiyam — CHANGES_REQUESTED** [review]
add tests for encode_separately and decode_separately

> Reviewed 5 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/27#-:-MHG2WXLDgLmpg9o4HER:b559yk7)* status: all files reviewed, 5 unresolved discussions (waiting on @golanha and @NassiHarel)

___
*[hkube_python_wrapper/communication/DataServer.py, line 30 at r4](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/27#-MHFz52R4C1tF_go-Ce0:-MHFz52S5DV3Bu7JWG65:b-7ioffh) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/fec4be12389dd289c5b5f264097a63d208a0d503/hkube_python_wrapper/communication/DataServer.py#L30)):*
> ```Python
>             decoded = self._encoding.decode(message, plain_encode=True)
>             tasks = decoded.get('tasks')
>             resultsAsTupple = self.getDataByTaskId(tasks)
> ```

tuple
___
*[hkube_python_wrapper/communication/DataServer.py, line 48 at r4](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/27#-MHFzXXP4R-riwsRjJO6:-MHFzXXP4R-riwsRjJO7:brij45v) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/fec4be12389dd289c5b5f264097a63d208a0d503/hkube_python_wrapper/communication/DataServer.py#L48)):*
> ```Python
>                 result = self.notAvailable
>             else:
>                 result = (self._cache.getHeader(task), self._cache.get(task))
> ```

join to one method that returns a tuple (same as encode)
___
*[hkube_python_wrapper/util/encoding.py, line 90 at r4](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/27#-MHG-WElA7Q2_B8pTnXv:-MHG-WElA7Q2_B8pTnXw:b-d0e8vm) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/fec4be12389dd289c5b5f264097a63d208a0d503/hkube_python_wrapper/util/encoding.py#L90)):*
> ```Python
>         return header, payload
> 
>     def encode(self, value, **kwargs):
> ```

change to implicit named params
___
*[hkube_python_wrapper/util/encoding.py, line 107 at r4](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/27#-MHG267F2T_7RWP7NnbR:-MHG267F2T_7RWP7NnbS:b-d0e8vm) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/fec4be12389dd289c5b5f264097a63d208a0d503/hkube_python_wrapper/util/encoding.py#L107)):*
> ```Python
>         return payload
> 
>     def decode(self, value, **kwargs):
> ```

change to implicit named params

**Review by golanha — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/27)* status: 4 of 11 files reviewed, 5 unresolved discussions (waiting on @NassiHarel and @yehiyam)

___
*[hkube_python_wrapper/communication/DataServer.py, line 30 at r4](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/27#-MHFz52R4C1tF_go-Ce0:-MHGe95f6thW9TWm4XCI:b-896fix) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/fec4be12389dd289c5b5f264097a63d208a0d503/hkube_python_wrapper/communication/DataServer.py#L30)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

tuple
</blockquote></details>

Done.
___
*[hkube_python_wrapper/communication/DataServer.py, line 48 at r4](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/27#-MHFzXXP4R-riwsRjJO6:-MHGiCL097gX3z74273H:b-896fix) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/fec4be12389dd289c5b5f264097a63d208a0d503/hkube_python_wrapper/communication/DataServer.py#L48)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

join to one method that returns a tuple (same as encode)
</blockquote></details>

Done.
___
*[hkube_python_wrapper/util/encoding.py, line 90 at r4](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/27#-MHG-WElA7Q2_B8pTnXv:-MHGil3V-7mS3GxORSFE:b-896fix) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/fec4be12389dd289c5b5f264097a63d208a0d503/hkube_python_wrapper/util/encoding.py#L90)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

change to implicit named params
</blockquote></details>

Done.
___
*[hkube_python_wrapper/util/encoding.py, line 107 at r4](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/27#-MHG267F2T_7RWP7NnbR:-MHGipIm3LSRk2eQ3Xja:b-896fix) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/fec4be12389dd289c5b5f264097a63d208a0d503/hkube_python_wrapper/util/encoding.py#L107)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

change to implicit named params
</blockquote></details>

Done.

**Review by yehiyam — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r5.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/27#-:-MHKpemiENsVoJ8S3-pp:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @NassiHarel)

**Review by NassiHarel — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/27#-:-MHL-wuBBGPxtKQp6Oka:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
