### PR TITLE
add wrapper::LEVEL:: prefix to logs

### PR DESCRIPTION
**Pull request by yehiyam**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/57)

### CODE REVIEW

**Comment by golanha** [comment]
___
*[stam.py, line 4 at r1](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/57#-MTUYJTkC_PVu09mig5V:-MTUYJTkC_PVu09mig5W:bxnak0h) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/9b8442331a949cb4ea6678fad254fa4204462d8b/stam.py#L4)):*
> ```
> log.info('fooo {fff}',fff='ggg')
> log.info(None)
> ```
Did you mean to submit this file?

**Review by golanha — COMMENTED** [review]
> Reviewed 25 of 25 files at r1.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/57)* status: all files reviewed, 1 unresolved discussion (waiting on @NassiHarel and @yehiyam)

**Review by yehiyam — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/57)* status: all files reviewed, 1 unresolved discussion (waiting on @golanha and @NassiHarel)

___
*[stam.py, line 4 at r1](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/57#-MTUYJTkC_PVu09mig5V:-MTUbm2WA7nr0dx2bSRv:b-896fix) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/9b8442331a949cb4ea6678fad254fa4204462d8b/stam.py#L4)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

> ```
> log.info('fooo {fff}',fff='ggg')
> log.info(None)
> ```
Did you mean to submit this file?
</blockquote></details>

Done.

**Review by golanha — DISMISSED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/57)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @NassiHarel)

**Review by NassiHarel — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/57)* status: all files reviewed, 1 unresolved discussion (waiting on @yehiyam)

___
*[hkube_python_wrapper/cache/caching.py, line 25 at r2](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/57#-MTUowblBfiPzV0iieZT:-MTUowbm6Q9KYyaTizWg:brzq5rg) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/b083253ffa358f30113631a1288b02c9f5fcf90f/hkube_python_wrapper/cache/caching.py#L25)):*
> ```
> +
> ```

redundant +

**Review by NassiHarel — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/57)* status: all files reviewed, 2 unresolved discussions (waiting on @yehiyam)

___
*[hkube_python_wrapper/util/logger.py, line 18 at r2](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/57#-MTUqPR409OGCJeIlaEJ:-MTUqPR409OGCJeIlaEK:b-q6r6d3) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/b083253ffa358f30113631a1288b02c9f5fcf90f/hkube_python_wrapper/util/logger.py#L18)):*
> ```
> level = config.logging.get('level', 'INFO')
> ```

If I set the level to INFO, it will include "WARNING" and "ERROR"?

**Review by yehiyam — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/57)* status: 23 of 24 files reviewed, 2 unresolved discussions (waiting on @golanha and @NassiHarel)

___
*[hkube_python_wrapper/cache/caching.py, line 25 at r2](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/57#-MTUowblBfiPzV0iieZT:-MTUs3ox9WOsO05Qrium:b-896fix) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/b083253ffa358f30113631a1288b02c9f5fcf90f/hkube_python_wrapper/cache/caching.py#L25)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> +
> ```

redundant +
</blockquote></details>

Done.
___
*[hkube_python_wrapper/util/logger.py, line 18 at r2](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/57#-MTUqPR409OGCJeIlaEJ:-MTUrgq65XfIpv3TvMea:b-3xjcl9) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/b083253ffa358f30113631a1288b02c9f5fcf90f/hkube_python_wrapper/util/logger.py#L18)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> level = config.logging.get('level', 'INFO')
> ```

If I set the level to INFO, it will include "WARNING" and "ERROR"?

</blockquote></details>

Yes. Info includes Info, Warning, Error, Critical...
From Info and worse

**Review by NassiHarel — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/57#-:-MTUsPLU0cPGXtwNKX_4:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by NassiHarel — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/57)* status: all files reviewed, 1 unresolved discussion (waiting on @yehiyam)

___
*[hkube_python_wrapper/util/logger.py, line 30 at r3](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/57#-MTUt1ZDAuERj9GBWFDM:-MTUt1ZE9r-KilqRNpkc:b5a7fl1) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/08cb4bd94d0c59f1055fe2307e55ffc15b7e79c3/hkube_python_wrapper/util/logger.py#L30)):*
> ```
> create console handler and set level to debug
> ```
debug? (copy-paste)

**Review by yehiyam — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/57)* status: 23 of 24 files reviewed, 1 unresolved discussion (waiting on @golanha and @NassiHarel)

___
*[hkube_python_wrapper/util/logger.py, line 30 at r3](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/57#-MTUt1ZDAuERj9GBWFDM:-MTUuyloBPQhN6P9mx3V:b-896fix) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/08cb4bd94d0c59f1055fe2307e55ffc15b7e79c3/hkube_python_wrapper/util/logger.py#L30)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> create console handler and set level to debug
> ```
debug? (copy-paste)
</blockquote></details>

Done.

**Pull request merged**
