### PR TITLE
1.3 fill missing pipeline result

### PR DESCRIPTION
**Pull request by golanha**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/45)

### CODE REVIEW

**Review by yehiyam — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/45)* status: all files reviewed, 1 unresolved discussion (waiting on @golanha)

___
*[hkube_python_wrapper/codeApi/hkube_api.py, line 48 at r1](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/45#-MQQvW7c0F_EHzvG5SB-:-MQQvW7c0F_EHzvG5SB0:b-one4im) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/62a0c2bb40ade2be0827edbaad227194b387e365/hkube_python_wrapper/codeApi/hkube_api.py#L48)):*
> ```
> v3
> ```
there is no v3 here

**Review by yehiyam — APPROVED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/45)* status: all files reviewed, 1 unresolved discussion (waiting on @golanha)

**Review by golanha — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/45)* status: all files reviewed, 1 unresolved discussion (waiting on @yehiyam)

___
*[hkube_python_wrapper/codeApi/hkube_api.py, line 48 at r1](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/45#-MQQvW7c0F_EHzvG5SB-:-MQfCrxq1Kvo16hfJxGM:bb7f2mf) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/62a0c2bb40ade2be0827edbaad227194b387e365/hkube_python_wrapper/codeApi/hkube_api.py#L48)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

> ```
> v3
> ```
there is no v3 here

</blockquote></details>

done

**Review by yehiyam — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/45)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @golanha)

**Pull request merged**
