### PR TITLE
feat: add multi-part storage method

### PR DESCRIPTION
**Pull request by NassiHarel**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/28)

### CODE REVIEW

**Review by yehiyam — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/28)* status: 0 of 17 files reviewed, 1 unresolved discussion (waiting on @NassiHarel and @yehiyam)

___
*[hkube_python_wrapper/util/encoding.py, line 132 at r1](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/28#-MHpppVC4aI3t0kjm6eY:-MHpppVD7ySqgtUwYmrV:b-evvdd0) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/624a152bc3070683e9645745e4676b93fde768a4/hkube_python_wrapper/util/encoding.py#L132)):*
> ```Python
>     def hexlify(value):
>         hex_data = binascii.hexlify(value)
>         return hex_data.decode('utf-8')
> ```

Use Base64. It is more standard and portable

**Review by golanha — CHANGES_REQUESTED** [review]
> Reviewed 7 of 17 files at r1, 9 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/28)* status: all files reviewed, 2 unresolved discussions (waiting on @NassiHarel)

___
*[hkube_python_wrapper/wrapper/data_adapter.py, line 28 at r2](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/28#-MHu4Wjh1x_n4JnV0zUP:-MHu4Wjh1x_n4JnV0zUQ:b-rkr8rv) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/b3ad7e735a7318845142e59ca3ca4fc1a2392ace/hkube_python_wrapper/wrapper/data_adapter.py#L28)):*
> ```
>     def encode(self, value):
>         return self._encoding.encode(value)
> ```
encode not used any longer, 
can be removed or change the encode_separately of data_adapter to be named encode for simplicity

**Review by NassiHarel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/28)* status: 8 of 16 files reviewed, 2 unresolved discussions (waiting on @golanha and @yehiyam)

___
*[hkube_python_wrapper/util/encoding.py, line 132 at r1](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/28#-MHpppVC4aI3t0kjm6eY:-MHuDHOVEaOKczNXw0b1:b-896fix) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/624a152bc3070683e9645745e4676b93fde768a4/hkube_python_wrapper/util/encoding.py#L132)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

Use Base64. It is more standard and portable
</blockquote></details>

Done.
___
*[hkube_python_wrapper/wrapper/data_adapter.py, line 28 at r2](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/28#-MHu4Wjh1x_n4JnV0zUP:-MHuJgyeBjNYs_rbOr2s:b-896fix) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/b3ad7e735a7318845142e59ca3ca4fc1a2392ace/hkube_python_wrapper/wrapper/data_adapter.py#L28)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

> ```
>     def encode(self, value):
>         return self._encoding.encode(value)
> ```
encode not used any longer, 
can be removed or change the encode_separately of data_adapter to be named encode for simplicity
</blockquote></details>

Done.

**Review by yehiyam — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r3.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/28)* status: all files reviewed, 3 unresolved discussions (waiting on @golanha and @NassiHarel)

___
*[hkube_python_wrapper/util/encoding.py, line 22 at r3](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/28#-MHvAc3x4V8gnR3z49Zz:-MHvAc3y8LR829vzr7mj:brxopnd) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/0e4c7d4625ee2b879e23cd4edea1da37e61a4edd/hkube_python_wrapper/util/encoding.py#L22)):*
> ```Python
> PY3 = sys.version_info[0] == 3
> 
> encodeBase64 = base64.encodebytes if PY3 else base64.encodestring
> ```

why encodebytes and not b64encode? 
___
*[hkube_python_wrapper/util/encoding.py, line 108 at r3](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/28#-MHv8wHz3y7VY05MyINX:-MHv8wI--0d-h8lZh7lg:b-ohmbse) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/0e4c7d4625ee2b879e23cd4edea1da37e61a4edd/hkube_python_wrapper/util/encoding.py#L108)):*
> ```Python
> 
>         sepHeaderLength = HEADER_LENGTH
>         if(header is None):
> ```

this is for compatibility with how it is written today?

**Review by NassiHarel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/28)* status: all files reviewed, 3 unresolved discussions (waiting on @golanha and @yehiyam)

___
*[hkube_python_wrapper/util/encoding.py, line 22 at r3](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/28#-MHvAc3x4V8gnR3z49Zz:-MHvEfZf29-FSwtSiT1f:b-rdqf48) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/0e4c7d4625ee2b879e23cd4edea1da37e61a4edd/hkube_python_wrapper/util/encoding.py#L22)):*
> b64encode
Do you mean  base64.encode?

From python 2.7 docs:
base64.encode(input, output)
Encode the contents of the input file and write the resulting base64 encoded data to the output file.
___
*[hkube_python_wrapper/util/encoding.py, line 108 at r3](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/28#-MHv8wHz3y7VY05MyINX:-MHvG3hu5ChFowTI7_Vp:b-puxyef) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/0e4c7d4625ee2b879e23cd4edea1da37e61a4edd/hkube_python_wrapper/util/encoding.py#L108)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

this is for compatibility with how it is written today?
</blockquote></details>

Yes, we will remove it.

**Review by NassiHarel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/28)* status: 12 of 16 files reviewed, 2 unresolved discussions (waiting on @golanha and @yehiyam)

___
*[hkube_python_wrapper/util/encoding.py, line 22 at r3](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/28#-MHvAc3x4V8gnR3z49Zz:-MHvRsxY35ZyS1EHS1I7:b-896fix) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/0e4c7d4625ee2b879e23cd4edea1da37e61a4edd/hkube_python_wrapper/util/encoding.py#L22)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> b64encode
Do you mean  base64.encode?

From python 2.7 docs:
base64.encode(input, output)
Encode the contents of the input file and write the resulting base64 encoded data to the output file.
</blockquote></details>

Done.

**Review by yehiyam — APPROVED** [review]
> Reviewed 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/28)* status: all files reviewed, 1 unresolved discussion (waiting on @golanha)

**Review by yehiyam — APPROVED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/28)* status: all files reviewed, 1 unresolved discussion (waiting on @golanha)

**Review by yehiyam — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/28#-:-MHz0bKe0jr85nVKvTIA:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @golanha)

**Pull request merged**
