### PR TITLE
Fix algorithm exit

### PR DESCRIPTION
**Pull request by yehiyam**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/29)

### CODE REVIEW

**Comment by yehiyam** [comment]
fixes kube-HPC/hkube#941

**Review by NassiHarel — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/29)* status: all files reviewed, 2 unresolved discussions (waiting on @yehiyam)

___
*[hkube_python_wrapper/util/timerImpl.py, line 28 at r2](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/29#-MHqeA2N5GW6EO8WvAPh:-MHqeA2OEzOH_rrHoNz9:buze7et) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/eb161f5e8b1c99b568433a8a6775661a7ff26658/hkube_python_wrapper/util/timerImpl.py#L28)):*
> ```Python
>             self._timer.name = self.name
>             self._timer.daemon = self.daemon
>             self._timer.start()
> ```

Is this code will work?

```
if (sys.version_info > (3, 0)):
    TimerClass = threading.Timer
else:
    TimerClass = threading._Timer


class Timer(TimerClass):
    def __init__(self, interval, function, args=None, kwargs=None, name='', daemon=False):
        super(Timer, self)__init__(interval, function, args, kwargs)
        self.name = name
        self.daemon = daemon
```
___
*[hkube_python_wrapper/wrapper/algorunner.py, line 367 at r2](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/29#-MHqe_uA5TeWrCttoY0J:-MHqe_uA5TeWrCttoY0K:bnwlbu4) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/eb161f5e8b1c99b568433a8a6775661a7ff26658/hkube_python_wrapper/wrapper/algorunner.py#L367)):*
> ```
> os._exit(0)
> ```
what is this? is it different form sys.exit(code) ?

**Review by yehiyam — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/29)* status: all files reviewed, 2 unresolved discussions (waiting on @NassiHarel)

___
*[hkube_python_wrapper/util/timerImpl.py, line 28 at r2](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/29#-MHqeA2N5GW6EO8WvAPh:-MHqm53nEFAzD7Z0gLAH:b-29753x) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/eb161f5e8b1c99b568433a8a6775661a7ff26658/hkube_python_wrapper/util/timerImpl.py#L28)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

Is this code will work?


if (sys.version_info > (3, 0)):
    Timer = threading.Timer
else:
    Timer = threading._Timer


class Timer(Timer):
    def __init__(self, interval, function, args=None, kwargs=None, name='', daemon=False):
        threading.Timer.__init__(self, interval, function, args, kwargs)
        self.name = name
        self.daemon = daemon

</blockquote></details>

In python 2.7 threading.Timer is not a class. There is an internal class called _Timer
___
*[hkube_python_wrapper/wrapper/algorunner.py, line 367 at r2](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/29#-MHqe_uA5TeWrCttoY0J:-MHqm_J7EpR41Z9nGDlV:b-flbai5) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/eb161f5e8b1c99b568433a8a6775661a7ff26658/hkube_python_wrapper/wrapper/algorunner.py#L367)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> os._exit(0)
> ```
what is this?
</blockquote></details>

That's like exit, but send SIGTERM and not SIGINT. It should kill the process. It is for worse case

**Review by yehiyam — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/29)* status: all files reviewed, 2 unresolved discussions (waiting on @NassiHarel)

___
*[hkube_python_wrapper/util/timerImpl.py, line 28 at r2](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/29#-MHqeA2N5GW6EO8WvAPh:-MHtRI8DCnQ96QuEBbes:b9rf263) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/eb161f5e8b1c99b568433a8a6775661a7ff26658/hkube_python_wrapper/util/timerImpl.py#L28)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

In python 2.7 threading.Timer is not a class. There is an internal class called _Timer
</blockquote></details>

I'd rather not call an internal class (even if it is python 2.7 and not likely to change)

**Pull request merged**
