### PR TITLE
feat: add report serving

### PR DESCRIPTION
**Pull request by NassiHarel**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/21)

### CODE REVIEW

**Review by yehiyam — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/21)* status: 5 of 6 files reviewed, 3 unresolved discussions (waiting on @golanha, @NassiHarel, and @yehiyam)

___
*[hkube_python_wrapper/config/config.py, line 29 at r1](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/21#-MG7_sdA9GaCbk_xwHxX:-MG7_sdB1fFQzKBLQUpW:btld9qz) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/d1118da4349e07b42cf4e54abe0e24021a2ba6c0/hkube_python_wrapper/config/config.py#L29)):*
> ```Python
>     "networkTimeout": getIntEnv('DISCOVERY_NETWORK_TIMEOUT', 1000),
>     "maxCacheSize": getIntEnv('DISCOVERY_MAX_CACHE_SIZE_MB', 400),
>     "servingReportInterval": getIntEnv('DISCOVERY_SERVING_REPORT_INTERVAL', 5000),
> ```

We need to add it to the template in task-executor
task-executor/lib/templates/worker.js
___
*[hkube_python_wrapper/wrapper/algorunner.py, line 292 at r1](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/21#-MG7cTLt55LesQt_plhq:-MG7cTLt55LesQt_plhr:b-7et6no) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/d1118da4349e07b42cf4e54abe0e24021a2ba6c0/hkube_python_wrapper/wrapper/algorunner.py#L292)):*
> ```Python
> 
>         def reportInterval(interval, event):
>             while not event.wait(interval):
> ```

Is this the "best practice" in python to create a timer? 
___
*[tests/test_communication.py, line 13 at r1](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/21#-MG7crJn-2RbBbJ0IAVx:-MG7crJn-2RbBbJ0IAVy:b-mls43i) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/d1118da4349e07b42cf4e54abe0e24021a2ba6c0/tests/test_communication.py#L13)):*
> ```Python
> 
> 
> def xtest_load_algorithm_callbacks():
> ```

Is it possible to add real tests for this?

**Review by yehiyam — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/21)* status: all files reviewed, 3 unresolved discussions (waiting on @golanha and @NassiHarel)

**Review by NassiHarel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/21)* status: all files reviewed, 3 unresolved discussions (waiting on @golanha and @yehiyam)

___
*[hkube_python_wrapper/config/config.py, line 29 at r1](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/21#-MG7_sdA9GaCbk_xwHxX:-MG7jgN9A8bC20W9y4xP:b-896fix) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/d1118da4349e07b42cf4e54abe0e24021a2ba6c0/hkube_python_wrapper/config/config.py#L29)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

We need to add it to the template in task-executor
task-executor/lib/templates/worker.js
</blockquote></details>

Done.
___
*[hkube_python_wrapper/wrapper/algorunner.py, line 292 at r1](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/21#-MG7cTLt55LesQt_plhq:-MG7iUgkAmdsVvBuMCjt:bsq1w6h) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/d1118da4349e07b42cf4e54abe0e24021a2ba6c0/hkube_python_wrapper/wrapper/algorunner.py#L292)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

Is this the "best practice" in python to create a timer? 
</blockquote></details>

This is one way, I can use gevent instead...
___
*[tests/test_communication.py, line 13 at r1](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/21#-MG7crJn-2RbBbJ0IAVx:-MG7k-mVBTPK4PalUII9:but1u66) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/d1118da4349e07b42cf4e54abe0e24021a2ba6c0/tests/test_communication.py#L13)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

Is it possible to add real tests for this?
</blockquote></details>

I didn't test it yet, even with an integration test.

**Review by NassiHarel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/21)* status: 4 of 7 files reviewed, 3 unresolved discussions (waiting on @golanha and @yehiyam)

___
*[hkube_python_wrapper/wrapper/algorunner.py, line 292 at r1](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/21#-MG7cTLt55LesQt_plhq:-MG7y8Q93ZMk2lTDWU-q:b-896fix) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/d1118da4349e07b42cf4e54abe0e24021a2ba6c0/hkube_python_wrapper/wrapper/algorunner.py#L292)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

This is one way, I can use gevent instead...
</blockquote></details>

Done.
___
*[tests/test_communication.py, line 13 at r1](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/21#-MG7crJn-2RbBbJ0IAVx:-MG7y9yr-IWu5-b2PIvo:b-896fix) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/d1118da4349e07b42cf4e54abe0e24021a2ba6c0/tests/test_communication.py#L13)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

I didn't test it yet, even with an integration test.
</blockquote></details>

Done.

**Review by golanha — APPROVED** [review]

**Review by golanha — APPROVED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/21)* status: all files reviewed, 3 unresolved discussions (waiting on @yehiyam)

**Review by yehiyam — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/21#-:-MG8mpfu4Z2_J5Deqk65:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @NassiHarel)

___
*[hkube_python_wrapper/wrapper/algorunner.py, line 292 at r1](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/21#-MG7cTLt55LesQt_plhq:-MG8mXC643N39i4GSB1e:b-w2m8in) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/d1118da4349e07b42cf4e54abe0e24021a2ba6c0/hkube_python_wrapper/wrapper/algorunner.py#L292)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

It's not that I prefer one or the other.

**Pull request merged**
