### PR TITLE
check cache before referring to peer

### PR DESCRIPTION
**Pull request by golanha**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/20)

### CODE REVIEW

**Review by NassiHarel — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/20)* status: all files reviewed, 2 unresolved discussions (waiting on @golanha and @yehiyam)

___
*[hkube_python_wrapper/wrapper/data_adapter.py, line 25 at r2](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/20#-MFdaUm_9wBc4h9Nw0Mc:-MFdaUm_9wBc4h9Nw0Md:b-np6h78) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/3e232c7126f4a9a208433b1459278cdcb407b51a/hkube_python_wrapper/wrapper/data_adapter.py#L25)):*
> ```
>  print('using {workers} for DataAdapter'.format(
>             workers=self._maxWorkers))
> ```

remove this new line format from the IDE....
The code looks very strange...
___
*[hkube_python_wrapper/wrapper/data_adapter.py, line 177 at r2](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/20#-MFddFWDE0logKFOo_uo:-MFddFWDE0logKFOo_up:baxr9sx) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/3e232c7126f4a9a208433b1459278cdcb407b51a/hkube_python_wrapper/wrapper/data_adapter.py#L177)):*
> ```
> if (self._dataServer and self._dataServer.isLocal(host, port)):
> ```

What about this use-case?

**Review by yehiyam — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/20)* status: all files reviewed, 3 unresolved discussions (waiting on @golanha)

___
*[setup.py, line 25 at r2](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/20#-MFdfUdB84I-fu29BX5L:-MFdfUdB84I-fu29BX5M:b800fka) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/3e232c7126f4a9a208433b1459278cdcb407b51a/setup.py#L25)):*
> ```Python
>     "pyzmq",
>     "jaeger-client==4",
>     "pympler"
> ```

didn't we remove it? maybe you need to update from master

**Comment by golanha** [comment]
___
*[setup.py, line 25 at r2](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/20#-MFdfUdB84I-fu29BX5L:-MFdusbv2vPuD60ghUeO:b-gzwony) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/3e232c7126f4a9a208433b1459278cdcb407b51a/setup.py#L25)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

didn't we remove it? maybe you need to update from master
</blockquote></details>

I put it back.
because now I put data that I got from peer to cache.
Generally I can check the size of what I get from peer before I decode it.
But in one case, where I ask peer for data of tasks (many), I get results of many tasks together. I decode it and add each separately to cache. I need to use the asizeof() to determine the size of each result.

**Review by golanha — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/20)* status: all files reviewed, 3 unresolved discussions (waiting on @NassiHarel and @yehiyam)

___
*[setup.py, line 25 at r2](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/20#-MFdfUdB84I-fu29BX5L:-MFdvvcLB1eZUx_EtWCL:b-896fix) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/3e232c7126f4a9a208433b1459278cdcb407b51a/setup.py#L25)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

I put it back.
because now I put data that I got from peer to cache.
Generally I can check the size of what I get from peer before I decode it.
But in one case, where I ask peer for data of tasks (many), I get results of many tasks together. I decode it and add each separately to cache. I need to use the asizeof() to determine the size of each result. 
</blockquote></details>

Done.
___
*[hkube_python_wrapper/wrapper/data_adapter.py, line 25 at r2](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/20#-MFdaUm_9wBc4h9Nw0Mc:-MFdw9U1CkFZyzOvlxs6:b-896fix) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/3e232c7126f4a9a208433b1459278cdcb407b51a/hkube_python_wrapper/wrapper/data_adapter.py#L25)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
>  print('using {workers} for DataAdapter'.format(
>             workers=self._maxWorkers))
> ```

remove this new line format from the IDE....
The code looks very strange...
</blockquote></details>

Done.
___
*[hkube_python_wrapper/wrapper/data_adapter.py, line 177 at r2](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/20#-MFddFWDE0logKFOo_uo:-MFe-LwqA9jBT9ThgP1w:b-os2veq) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/3e232c7126f4a9a208433b1459278cdcb407b51a/hkube_python_wrapper/wrapper/data_adapter.py#L177)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> if (self._dataServer and self._dataServer.isLocal(host, port)):
> ```

What about this use-case?

</blockquote></details>

You are right.
In this case, I will set the size to 0, since its already taken in to consideration as part of the DataServer cache.

**Review by golanha — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/20)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @NassiHarel and @yehiyam)

___
*[hkube_python_wrapper/wrapper/data_adapter.py, line 177 at r2](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/20#-MFddFWDE0logKFOo_uo:-MFe1TB9DfBjeImikNca:bdpme8p) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/3e232c7126f4a9a208433b1459278cdcb407b51a/hkube_python_wrapper/wrapper/data_adapter.py#L177)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

You are right.
In this case, I will set the size to 0, since its already taken in to consideration as part of the DataServer cache.
</blockquote></details>

On second thought, I will not add it to cache at all since later on , it may be removed from the DataServer cache, and not calculated  as part of the in storagecache.

**Review by NassiHarel — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/20)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @golanha, @NassiHarel, and @yehiyam)

___
*[hkube_python_wrapper/wrapper/data_adapter.py, line 113 at r4](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/20#-MFeWUG0E2qN9XHyuGnM:-MFeWUG16EQWt3DhnKV6:b8pohc) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/22c584b095413c5a0d5292f8d1d3cfcb32c39bcc/hkube_python_wrapper/wrapper/data_adapter.py#L113)):*
> ```
> for t in tasks:
> ```

is it iterates all tasks or tasksNotInCache?

**Review by golanha — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/20)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @NassiHarel and @yehiyam)

___
*[hkube_python_wrapper/wrapper/data_adapter.py, line 113 at r4](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/20#-MFeWUG0E2qN9XHyuGnM:-MFeeMpP4pek9y3FbAJo:b-svfihy) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/22c584b095413c5a0d5292f8d1d3cfcb32c39bcc/hkube_python_wrapper/wrapper/data_adapter.py#L113)):*
> ```
> for t in tasks
>
Should be tasksNotInCache, I'll correct it.

**Review by NassiHarel — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/20#-:-MFez5Fp6w3sjniLp0CT:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @golanha and @yehiyam)

___
*[hkube_python_wrapper/wrapper/data_adapter.py, line 86 at r5](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/20#-MFexd9LCz4af26Li4NF:-MFexd9LCz4af26Li4NG:b611syh) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/8053b3bdcff4e9ae6f6314c1ead58a774b4eefb3/hkube_python_wrapper/wrapper/data_adapter.py#L86)):*
> ```
> pylint: disable=too-many-branches
> ```
Pylint is right, it has become too complicated and it will be very hard to do unit-tests with full coverage.

**Review by golanha — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/20)* status: 3 of 6 files reviewed, 2 unresolved discussions (waiting on @NassiHarel and @yehiyam)

___
*[hkube_python_wrapper/wrapper/data_adapter.py, line 86 at r5](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/20#-MFexd9LCz4af26Li4NF:-MFy3kjh19q7UAwtpG-i:b-896fix) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/8053b3bdcff4e9ae6f6314c1ead58a774b4eefb3/hkube_python_wrapper/wrapper/data_adapter.py#L86)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> pylint: disable=too-many-branches
> ```
Pylint is right, it has become too complicated and it will be very hard to do unit-tests with full coverage.
</blockquote></details>

Done.

**Review by NassiHarel — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/20#-:-MG7S52i6zJwHYxkqycD:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @yehiyam)

**Pull request merged**
