### PR TITLE
Fill missing pipeline result

### PR DESCRIPTION
**Pull request by golanha**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/44)

### CODE REVIEW

**Review by yehiyam — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/44)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @golanha, @NassiHarel, and @yehiyam)

___
*[hkube_python_wrapper/wrapper/data_adapter.py, line 180 at r1](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/44#-MQ7Malt-em3l66aia4Z:-MQ7Malu8kaEfNLwWvCx:b-k6jhoq) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/d81441e684d4bfdd92ad7881c3c5bb9a3994f44f/hkube_python_wrapper/wrapper/data_adapter.py#L180)):*
> ```
> if options['path'].endswith('result.json'):
> ```
why do you need to check the file name? 

Also, why not do it in the HkubeApi class, right after you get the result?

**Review by NassiHarel — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/44)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @golanha and @NassiHarel)

___
*[hkube_python_wrapper/wrapper/data_adapter.py, line 180 at r1](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/44#-MQ7SlXf-QFQ8_ZbghSw:-MQ7SlXg7-Z8ZouoIhJ_:b3n0z1z) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/d81441e684d4bfdd92ad7881c3c5bb9a3994f44f/hkube_python_wrapper/wrapper/data_adapter.py#L180)):*
> ```
>  if options['path'].endswith('result.json'):
> ```

If you put this code inside hkubeApi after the sub-pipeline has done, you wouldn't need all this hacking.

**Review by NassiHarel — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/44)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @golanha)

___
*[hkube_python_wrapper/codeApi/hkube_api.py, line 60 at r2](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/44#-MQ7YS3085Pi5xT73-Ay:-MQ7YS3176jIPirFtAjD:b-a02qg2) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/a31ef801c2f197ae2a8bf5736c14111574ea182e/hkube_python_wrapper/codeApi/hkube_api.py#L60)):*
> ```
> for node in result:
> ```
This code runs also right after code-api algorithm done, did you check what will happen?

**Review by NassiHarel — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/44)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @golanha)

___
*[hkube_python_wrapper/codeApi/hkube_api.py, line 60 at r3](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/44#-MQ7f1d04T6uTNCX-nVq:-MQ7f1d13r3A9wA87VMY:bifgawn) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/bbfffcf1444ba2a6a00654b0ecca494528521a77/hkube_python_wrapper/codeApi/hkube_api.py#L60)):*
> ```
>  if hasattr(result, "__len__"):
> ```

We have `type_check.isList`

**Review by NassiHarel — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/44)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @golanha)

___
*[hkube_python_wrapper/codeApi/hkube_api.py, line 60 at r4](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/44#-MQ7pfkY8kzjtArjwyiE:-MQ7pfkY8kzjtArjwyiF:bqvzkwb) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/1617947fa3b157dcc0f84504a24510d99bc33f5e/hkube_python_wrapper/codeApi/hkube_api.py#L60)):*
> ```
> if hasattr(result, "__len__"):
> ```
Why?

**Review by golanha — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/44)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @NassiHarel and @yehiyam)

___
*[hkube_python_wrapper/codeApi/hkube_api.py, line 60 at r2](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/44#-MQ7YS3085Pi5xT73-Ay:-MQ7sc172suph5pYiog8:b-896fix) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/a31ef801c2f197ae2a8bf5736c14111574ea182e/hkube_python_wrapper/codeApi/hkube_api.py#L60)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> for node in result:
> ```
This code runs also right after code-api algorithm done, did you check what will happen?
</blockquote></details>

Done.
___
*[hkube_python_wrapper/codeApi/hkube_api.py, line 60 at r3](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/44#-MQ7f1d04T6uTNCX-nVq:-MQ7saPt5J7GjTcyTOHX:b-896fix) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/bbfffcf1444ba2a6a00654b0ecca494528521a77/hkube_python_wrapper/codeApi/hkube_api.py#L60)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
>  if hasattr(result, "__len__"):
> ```

We have `type_check.isList`
</blockquote></details>

Done.
___
*[hkube_python_wrapper/codeApi/hkube_api.py, line 60 at r4](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/44#-MQ7pfkY8kzjtArjwyiE:-MQ7safgDV1DatvE_6gl:b-896fix) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/1617947fa3b157dcc0f84504a24510d99bc33f5e/hkube_python_wrapper/codeApi/hkube_api.py#L60)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> if hasattr(result, "__len__"):
> ```
Why?
</blockquote></details>

Done.
___
*[hkube_python_wrapper/wrapper/data_adapter.py, line 180 at r1](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/44#-MQ7Malt-em3l66aia4Z:-MQ7Nqj30RCI9O2bAb7q:b-a4y87z) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/d81441e684d4bfdd92ad7881c3c5bb9a3994f44f/hkube_python_wrapper/wrapper/data_adapter.py#L180)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

> ```
> if options['path'].endswith('result.json'):
> ```
why do you need to check the file name? 

Also, why not do it in the HkubeApi class, right after you get the result?
</blockquote></details>

I thought by checking the name I make sure I only deal with a pipeline result, so I won't make the other checks upon every access to the storage.
I can move it to subpipeline done part, then I won't check the file name.
___
*[hkube_python_wrapper/wrapper/data_adapter.py, line 180 at r1](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/44#-MQ7SlXf-QFQ8_ZbghSw:-MQ7shB_Dv-e1zQf12uh:b-896fix) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/d81441e684d4bfdd92ad7881c3c5bb9a3994f44f/hkube_python_wrapper/wrapper/data_adapter.py#L180)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
>  if options['path'].endswith('result.json'):
> ```

If you put this code inside hkubeApi after the sub-pipeline has done, you wouldn't need all this hacking.

</blockquote></details>

Done.

**Review by yehiyam — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/44)* status: all files reviewed, 5 unresolved discussions (waiting on @golanha and @NassiHarel)

___
*[hkube_python_wrapper/codeApi/hkube_api.py, line 63 at r5](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/44#-MQBHON-Blo08otIIiqE:-MQBHON-Blo08otIIiqF:byaqe10) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/1ef9e8eb1db60a5a7ec288dd602f68464692f73b/hkube_python_wrapper/codeApi/hkube_api.py#L63)):*
> ```
> typeCheck.isDict(node) and node.get('info') is not None and node['info']['isBigData']:
> ```
you can use https://github.com/kube-HPC/python-wrapper.hkube/blob/75c31947c6eb6bd31d69ac4ab276c6cbf9fcec25/hkube_python_wrapper/util/object_path.py#L5

**Review by golanha — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/44)* status: 1 of 2 files reviewed, 5 unresolved discussions (waiting on @NassiHarel and @yehiyam)

___
*[hkube_python_wrapper/codeApi/hkube_api.py, line 63 at r5](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/44#-MQBHON-Blo08otIIiqE:-MQBP2OE63NlRJHkvx3W:bb6un1j) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/1ef9e8eb1db60a5a7ec288dd602f68464692f73b/hkube_python_wrapper/codeApi/hkube_api.py#L63)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

> ```
> typeCheck.isDict(node) and node.get('info') is not None and node['info']['isBigData']:
> ```
you can use https://github.com/kube-HPC/python-wrapper.hkube/blob/75c31947c6eb6bd31d69ac4ab276c6cbf9fcec25/hkube_python_wrapper/util/object_path.py#L5
</blockquote></details>

Done

**Review by yehiyam — DISMISSED** [review]
looks OK. Try to add tests

> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/44#-:-MQBsdql1xYP6J0H6xMV:b96ov1d)* status: all files reviewed, 4 unresolved discussions (waiting on @NassiHarel)

**Pull request merged**
