### PR TITLE
Handle already connected for debug

### PR DESCRIPTION
**Pull request by golanha**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/77)

### CODE REVIEW

**Review by yehiyam — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/77)* status: all files reviewed, 1 unresolved discussion (waiting on @golanha and @NassiHarel)

___
*[hkube_python_wrapper/wrapper/wc.py, line 44 at r3](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/77#-MfgUm-UExDXPRDhDJOe:-MfgUm-V2CXYZFroAiC4:b-8z507a) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/4723264c1030409b249b7ffd085bedd8dda17692/hkube_python_wrapper/wrapper/wc.py#L44)):*
> ```Python
>         # pylint: disable=unused-argument
>         if (code == 1013):
>             log.error('Other client already connected for debug')
> ```

Another client is already connected for debug

**Review by NassiHarel — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/77)* status: all files reviewed, 1 unresolved discussion (waiting on @yehiyam)

___
*[hkube_python_wrapper/wrapper/wc.py, line 44 at r3](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/77#-MfgUm-UExDXPRDhDJOe:-MfgVdeh34MKiS8wLufE:bnlnd7l) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/4723264c1030409b249b7ffd085bedd8dda17692/hkube_python_wrapper/wrapper/wc.py#L44)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

Another client is already connected for debug
</blockquote></details>

If you change, so also here:
https://github.com/kube-HPC/nodejs-wrapper.hkube/blob/354d906546a6a62ff5436ecf869b202f40fcbc03/lib/websocket/ws.js#L58

**Review by yehiyam — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/77)* status: all files reviewed, 1 unresolved discussion (waiting on @NassiHarel)

___
*[hkube_python_wrapper/wrapper/wc.py, line 44 at r3](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/77#-MfgUm-UExDXPRDhDJOe:-MfgVzZCCNN2Dgip08Et:bzdgtco) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/4723264c1030409b249b7ffd085bedd8dda17692/hkube_python_wrapper/wrapper/wc.py#L44)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

If you change, so also here:
https://github.com/kube-HPC/nodejs-wrapper.hkube/blob/354d906546a6a62ff5436ecf869b202f40fcbc03/lib/websocket/ws.js#L58
</blockquote></details>

Also, I think it will be better if we don't reconnect, but exit the process

**Review by NassiHarel — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/77)* status: all files reviewed, 1 unresolved discussion (waiting on @yehiyam)

___
*[hkube_python_wrapper/wrapper/wc.py, line 44 at r3](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/77#-MfgUm-UExDXPRDhDJOe:-MfgZ7pTA2dbtDFPVJxI:b-41uf1b) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/4723264c1030409b249b7ffd085bedd8dda17692/hkube_python_wrapper/wrapper/wc.py#L44)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

Also, I think it will be better if we don't reconnect, but exit the process
</blockquote></details>

Or at least print "reconnecting in 3 2 1....."

**Review by golanha — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/77)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @yehiyam)

___
*[hkube_python_wrapper/wrapper/wc.py, line 44 at r3](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/77#-MfgUm-UExDXPRDhDJOe:-Mfgo9PC4rq42GA1odC8:b-896fix) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/4723264c1030409b249b7ffd085bedd8dda17692/hkube_python_wrapper/wrapper/wc.py#L44)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

Or at least print "reconnecting in 3 2 1....."
</blockquote></details>

Done.

**Review by yehiyam — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/77)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @golanha)

**Pull request merged**
