### PR TITLE
fix: PR issues

### PR DESCRIPTION
**Pull request by NassiHarel**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/69)

### CODE REVIEW

**Review by yehiyam — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/69)* status: all files reviewed, 1 unresolved discussion (waiting on @NassiHarel)

___
*[.pylintrc, line 14 at r1](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/69#-MVLtM3i69aVHA1fYGxm:-MVLtM3jC7zaorI894xi:b8cbw0) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/71560f9dd6c25525fca7993adc397a4ca3e4a08d/.pylintrc#L14)):*
> ```
> unused-wildcard-import
> ```
you can probably remove this

**Review by NassiHarel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/69)* status: 7 of 10 files reviewed, 1 unresolved discussion (waiting on @yehiyam)

___
*[.pylintrc, line 14 at r1](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/69#-MVLtM3i69aVHA1fYGxm:-MVLyrPj5cGXMXsZNSy8:b-896fix) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/71560f9dd6c25525fca7993adc397a4ca3e4a08d/.pylintrc#L14)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

> ```
> unused-wildcard-import
> ```
you can probably remove this
</blockquote></details>

Done.

**Review by yehiyam — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/69)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @NassiHarel and @yehiyam)

___
*[hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py, line 84 at r2](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/69#-MVM1nVgDd_huq7EkSQJ:-MVM1nVhA2zNqTsXsxgR:b-q428vo) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/0fa27adf2654ab5bd0789f5b569a66d4a7bc196b/hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py#L84)):*
> ```Python
> 
>                     if (signal == signals.PPP_MSG):
>                         # self.onNotReady() Segmentation fault (core dumped)
> ```

You're going to implement ready/not-ready another way?

**Review by yehiyam — COMMENTED** [review]
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/69)* status: all files reviewed, 1 unresolved discussion (waiting on @NassiHarel)

**Review by golanha — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r4, 10 of 10 files at r5.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/69)* status: all files reviewed, 6 unresolved discussions (waiting on @NassiHarel)

___
*[hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py, line 85 at r5](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/69#-MVlIpoi9IRvX5ciSVc3:-MVlIpoi9IRvX5ciSVc4:b-r6sgm0) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/9a911dfe92304385887d17357e46be3e93a254fe/hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py#L85)):*
> ```
> onNotReady
> ```
I would name it makeOthersNotReady' to make distinguish between  the local ready handling and other listeners ready handling.
___
*[hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py, line 87 at r5](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/69#-MVlJ8YI6AqawZL3SA0B:-MVlJ8YI6AqawZL3SA0C:b83z0r1) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/9a911dfe92304385887d17357e46be3e93a254fe/hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py#L87)):*
> ```
> onReady
> ```
makeOthersReady
___
*[hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py, line 124 at r5](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/69#-MVlDEV-EG9iTIxs1vDL:-MVlDEV01JRbUBxjLEvd:b3f7mo5) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/9a911dfe92304385887d17357e46be3e93a254fe/hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py#L124)):*
> ```Python
>             self._send(self._worker, signals.PPP_HEARTBEAT)
> 
>     def _checkReady(self):
> ```

The method name should be send, not check
___
*[hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py, line 172 at r5](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/69#-MVlEmci3AClMRsvopLg:-MVlEmci3AClMRsvopLh:b-aqumyb) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/9a911dfe92304385887d17357e46be3e93a254fe/hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py#L172)):*
> ```
> STOP_TIMEOUT_MS
> ```
I think since you sent a disconnect and went to sleep for 2 seconds the stop timeout can be very small a little  less than the time it takes to send a message.
___
*[hkube_python_wrapper/communication/zmq/streaming/producer/ZMQProducer.py, line 54 at r5](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/69#-MVlGf1l8l__NmQeuYvz:-MVlGf1l8l__NmQeuYw-:b-wlts0x) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/9a911dfe92304385887d17357e46be3e93a254fe/hkube_python_wrapper/communication/zmq/streaming/producer/ZMQProducer.py#L54)):*
> ```
>                     frames = self._backend.recv_multipart() or []
> ```
why do you allow this? when can this happen?

**Review by NassiHarel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/69)* status: all files reviewed, 6 unresolved discussions (waiting on @golanha, @NassiHarel, and @yehiyam)

___
*[hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py, line 84 at r2](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/69#-MVM1nVgDd_huq7EkSQJ:-MVlN77j4MFEEKM0MsNB:b-896fix) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/0fa27adf2654ab5bd0789f5b569a66d4a7bc196b/hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py#L84)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

You're going to implement ready/not-ready another way?
</blockquote></details>

Done.
___
*[hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py, line 124 at r5](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/69#-MVlDEV-EG9iTIxs1vDL:-MVlNFvv2XNBXZLl_z02:b-h5ouj1) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/9a911dfe92304385887d17357e46be3e93a254fe/hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py#L124)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

The method name should be send, not check
</blockquote></details>

We are not always send
___
*[hkube_python_wrapper/communication/zmq/streaming/producer/ZMQProducer.py, line 54 at r5](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/69#-MVlGf1l8l__NmQeuYvz:-MVlNPE19UHRI77hDpZt:b-qwz89) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/9a911dfe92304385887d17357e46be3e93a254fe/hkube_python_wrapper/communication/zmq/streaming/producer/ZMQProducer.py#L54)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

> ```
>                     frames = self._backend.recv_multipart() or []
> ```
why do you allow this? when can this happen?
</blockquote></details>

I want to validate I always got 4 frames

**Review by golanha — CHANGES_REQUESTED** [review]
In messageListener close, since you don't close immediately you can't clear the self.messageListeners = [],
these still need to be used for the last message.  

> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/69#-:-MVq8d2b3LArFGaU_B0q:b63sgno)* status: all files reviewed, 5 unresolved discussions (waiting on @NassiHarel and @yehiyam)

___
*[hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py, line 124 at r5](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/69#-MVlDEV-EG9iTIxs1vDL:-MVpq10v9DDxqokI16dx:bl40yxr) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/9a911dfe92304385887d17357e46be3e93a254fe/hkube_python_wrapper/communication/zmq/streaming/ZMQListener.py#L124)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

We are not always send
</blockquote></details>

Its "send if necessary", send would be enough

**Review by golanha — DISMISSED** [review]
> Reviewed 6 of 6 files at r6.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/69)* status: all files reviewed, 5 unresolved discussions (waiting on @NassiHarel and @yehiyam)

**Pull request merged**
