### PR TITLE
save statistics per consumer

### PR DESCRIPTION
**Pull request by golanha**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/41)

### CODE REVIEW

**Review by yehiyam — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/41)* status: all files reviewed, 4 unresolved discussions (waiting on @golanha)

___
*[hkube_python_wrapper/communication/zmq/streaming/producer/Flow.py, line 16 at r1](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/41#-MOBLeeG-2eh1hbOInVK:-MOBLeeG-2eh1hbOInVL:b-j0anbt) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/8a7429f6a7d76dbe96d284d96a1dd23967d90fff/hkube_python_wrapper/communication/zmq/streaming/producer/Flow.py#L16)):*
> ```Python
>             return []
>         flowcopy = self.flow[:]
>         flowcopy.remove(current)
> ```

isn't current always the first? If so you can just return from the second element (something like flow[1:]
___
*[hkube_python_wrapper/communication/zmq/streaming/producer/Flow.py, line 22 at r1](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/41#-MOBKzc6AzYtwW_dMMu3:-MOBKzc77J1iF4pnj8uF:bgwlhhl) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/8a7429f6a7d76dbe96d284d96a1dd23967d90fff/hkube_python_wrapper/communication/zmq/streaming/producer/Flow.py#L22)):*
> ```Python
>         current = None
>         for node in self.flow:
>             if current is None:
> ```

How can current be not None?
___
*[hkube_python_wrapper/communication/zmq/streaming/producer/MessageQueue.py, line 44 at r1](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/41#-MOBMOUPBXlAXyK9Cuxr:-MOBMOUPBXlAXyK9Cuxs:bsb41pb) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/8a7429f6a7d76dbe96d284d96a1dd23967d90fff/hkube_python_wrapper/communication/zmq/streaming/producer/MessageQueue.py#L44)):*
> ```Python
>     def pop(self, consumerType):
>         nextItemIndex = self.nextMessageIndex(consumerType)
>         if (nextItemIndex is not None):
> ```

just `if (nextItemIndex):` is enough
___
*[hkube_python_wrapper/communication/zmq/streaming/producer/ZMQProducer.py, line 93 at r1](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/41#-MOBNIzzCbI94bjD2oIF:-MOBNJ--9oxub8udIbNk:b21347f) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/8a7429f6a7d76dbe96d284d96a1dd23967d90fff/hkube_python_wrapper/communication/zmq/streaming/producer/ZMQProducer.py#L93)):*
> ```
> type
> ```
`type` is a class in python

**Review by golanha — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/41)* status: 6 of 7 files reviewed, 4 unresolved discussions (waiting on @yehiyam)

___
*[hkube_python_wrapper/communication/zmq/streaming/producer/Flow.py, line 16 at r1](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/41#-MOBLeeG-2eh1hbOInVK:-MOBOC7c9o2vRQuaqKFj:b7ymq84) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/8a7429f6a7d76dbe96d284d96a1dd23967d90fff/hkube_python_wrapper/communication/zmq/streaming/producer/Flow.py#L16)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

isn't current always the first? If so you can just return from the second element (something like flow[1:]
</blockquote></details>

no, its not always the first.
 [{'source': 'B', 'next': ['A', 'C']}, {'source': 'C', 'next': ['D']},{'source': 'A', 'next': ['E']}]
in this case when A gets the flow it will have C first and just ignore it.
___
*[hkube_python_wrapper/communication/zmq/streaming/producer/Flow.py, line 22 at r1](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/41#-MOBKzc6AzYtwW_dMMu3:-MOBOscL-y3kSHAOvThs:b-g6fvgu) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/8a7429f6a7d76dbe96d284d96a1dd23967d90fff/hkube_python_wrapper/communication/zmq/streaming/producer/Flow.py#L22)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

How can current be not None?
</blockquote></details>

first time in the loop it will none but next time its possible its not None if its not set yet
___
*[hkube_python_wrapper/communication/zmq/streaming/producer/MessageQueue.py, line 44 at r1](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/41#-MOBMOUPBXlAXyK9Cuxr:-MOBP9mB4ul9XAA_QJia:b-a6upci) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/8a7429f6a7d76dbe96d284d96a1dd23967d90fff/hkube_python_wrapper/communication/zmq/streaming/producer/MessageQueue.py#L44)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

just `if (nextItemIndex):` is enough
</blockquote></details>

0 is a possible value for the index
___
*[hkube_python_wrapper/communication/zmq/streaming/producer/ZMQProducer.py, line 93 at r1](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/41#-MOBNIzzCbI94bjD2oIF:-MOBPrw7-O5mBw1ITZPa:bye47nb) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/8a7429f6a7d76dbe96d284d96a1dd23967d90fff/hkube_python_wrapper/communication/zmq/streaming/producer/ZMQProducer.py#L93)):*
> ```
> for type, workerQueue in workers.queues.items()
> ```
renamed it

**Review by yehiyam — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/41)* status: all files reviewed, 3 unresolved discussions (waiting on @golanha and @yehiyam)

___
*[hkube_python_wrapper/communication/zmq/streaming/producer/Flow.py, line 22 at r1](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/41#-MOBKzc6AzYtwW_dMMu3:-MOC26vm4Amm2xUcLUWx:bnrlgau) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/8a7429f6a7d76dbe96d284d96a1dd23967d90fff/hkube_python_wrapper/communication/zmq/streaming/producer/Flow.py#L22)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

first time in the loop it will none but next time its possible its not None if its not set yet
</blockquote></details>

You set current in one place only - right before you return it. So if it is set, the statement `if current is None:` will never be executed again because you return.
___
*[hkube_python_wrapper/communication/zmq/streaming/producer/MessageQueue.py, line 44 at r1](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/41#-MOBMOUPBXlAXyK9Cuxr:-MOC2aoo7-dDS9ajr2-R:b-ipelyu) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/8a7429f6a7d76dbe96d284d96a1dd23967d90fff/hkube_python_wrapper/communication/zmq/streaming/producer/MessageQueue.py#L44)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

0 is a possible value for the index
</blockquote></details>

You are right :-)

**Review by golanha — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/41)* status: 6 of 7 files reviewed, 2 unresolved discussions (waiting on @yehiyam)

___
*[hkube_python_wrapper/communication/zmq/streaming/producer/Flow.py, line 22 at r1](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/41#-MOBKzc6AzYtwW_dMMu3:-MOPmFzt9apcuvT8VvTj:bumul67) ([raw file](https://github.com/kube-hpc/python-wrapper.hkube/blob/8a7429f6a7d76dbe96d284d96a1dd23967d90fff/hkube_python_wrapper/communication/zmq/streaming/producer/Flow.py#L22)):*
> ```
> def _getCurrent(self, currentName):
> ```
So true :-) Done

**Review by yehiyam — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/41)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by yehiyam — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/python-wrapper.hkube/41)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
